### PR TITLE
i have added works section and about sections to the previous header section

### PR DESCRIPTION
**Pull request by ndikumanaisaie**
this branch contains a mobile version with works and about sections which extends the header section of the previous project

### CODE REVIEW

**Review by chrystalme — CHANGES_REQUESTED** [review]
# Hi @ndikumanaisaie, 

You have done a good job so far!
However, there are some issues that you still need to work on to prepare your project for further evaluation

## Suggested changes ♻️ 

- [ ] Kindly use `<section>` tag for each new section of your portfolio


surround the highlighted portion with a `<section>` tag

- [ ] Kindly use `<section>` tag here 👇🏽  as well


- [ ] I observed that you have several `<h1>` tags in your document. It is semantically incorrect to have more than one `<h1>` heading in your HTML document.


## Optional Changes
You can also consider:
- [ ] renaming your index file to index.html rather than portfolio.html make it difficult to know the entry point of your application.
- [ ] making frequent commits. This makes it easier for you to revert back quite easily without losing much time.
- [ ] avoiding multiple pull requests and use easy descriptive phrase or sentence for your pull request. Example - `Review request for second milestone`

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by koomekevo — CHANGES_REQUESTED** [review]
Hi @ndikumanaisaie , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights
:heavy_check_mark: Your README is descriptive.
:heavy_check_mark: Your project has no linter errors.

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] There is still an issue with rendering background images as shown in the Figma template. As you can see in the below screenshot your project does not have background images. Kindly fix that.

ndikumanawrong

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ndikumanaisaie** [comment]
Oooh lala i have one last chance. Is it possible to do it tomorrow or i
must finish today

**Comment by ndikumanaisaie** [comment]
hallo in my computer it is working without doing any change

**Review by rloterh — APPROVED** [review]
Hi Isaie, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ndikumanaisaie** [comment]
Thank you!

**Comment by ndikumanaisaie** [comment]
I did not notice this because it was not concerned. I was concentrating on
changing what the previous reviewer told me to do

**Pull request merged**
